export const members = [{
        id: "d09e1f22cfe01ddbc69862860e06b7ea",
        firstName: "Alexandr",
        lastName: "Hambardzumyan",
        phone: "+374 93 11 44 15",
        email: "alexanhambarcumyan@gmail.com",
        education: "Shushi Technology university",
        workExperience: "AIPC",
        trainings: "RELQ school",
        imagePath: "./poto/AlexandrHambardzumyan.jpg",
    },
    {
        id: "8c955dc70dc31a9fc79720e62cdca8e6",
        firstName: "Anahit",
        lastName: "Khechumyan",
        phone: "+374 44 14 80 00",
        email: "Khechumyan63@gmail.com",
        education: "Yerevan State University",
        workExperience: "School Principal-School N67 Bitschool",
        trainings: "RELQ",
        imagePath: "./poto/AnahitKhechumyan.jpg",
    },
    {
        id: "b75d86579d575b2e97dc0815c9b32c91",
        firstName: "Ani",
        lastName: "Antonyan",
        phone: "notDefined",
        email: "notDefined",
        education: "notDefined",
        workExperience: "notDefined",
        trainings: "RELQ",
        imagePath: "./poto/AniAntonyan.jpg",
    },
    {
        id: "bdfcc948dc17e74c82eaae9ab54f6337",
        firstName: "Anna",
        lastName: "Hayriyan",
        phone: "+374 98 14 44 50",
        email: "annhayriyan@gmail.com",
        education: "ASUE",
        workExperience: "Scott logistics",
        trainings: "RELQ",
        imagePath: "./poto/AnnaHayriyan.jpg",
    },
    {
        id: "8eee77f518eebf21f1e6e9d18365b294",
        firstName: "Armenak",
        lastName: "Qocharyan",
        phone: "+374 94 90 21 71",
        email: "qocharyanarmenak@gmail.com",
        education: "Բարձրագույն զինվորական",
        workExperience: "ՀՀ ՊՆ",
        trainings: "Relq School",
        imagePath: "./poto/ArmenakQocharyan.jpg",
    },
    {
        id: "f9fcf999516d27e2be260de5bf822628",
        firstName: "Arusyak",
        lastName: "Aghajanyan",
        phone: "+374 55 90 01 55",
        email: "aghajanyanarusyak@gmail.com",
        education: "YSUGU",
        workExperience: "InecoBank CJSC, Risk meneger",
        trainings: "BasicItCenter,UNDP Armenia Accelerator5,HTI Armenia C++ basic, SmartCode,Relq Technology",
        imagePath: "./poto/ArusyakAghajanyan.jpg",
    },
    {
        id: "eca77b9eced01bbdbfd8e337f2eb3b7c",
        firstName: "Afina",
        lastName: "Panyan",
        phone: "notDefined",
        email: "notDefined",
        education: "notDefined",
        workExperience: "notDefined",
        trainings: "Relq",
        imagePath: "./poto/AfinaPanyan.jpg",
    },
    {
        id: "dfdafb5a1ebe81dce7505fa04badbe9c",
        firstName: "Babken",
        lastName: "Tadevosyan",
        phone: "+374 93 28 55 95",
        email: "notDefined",
        education: "notDefined",
        workExperience: "notDefined",
        trainings: "Relq",
        imagePath: "./poto/BabkenTadevosyan.jpg",
    },
    {
        id: "c5bf5032ef11ac0e8147c2921ba4c245",
        firstName: "Hasmik",
        lastName: "Gevorgyan",
        phone: "notDefined",
        email: "notDefined",
        education: "notDefined",
        workExperience: "notDefined",
        trainings: "Relq",
        imagePath: "./poto/HasmikGevorgyan.jpg",
    },
    {
        id: "922e51b2c63f2ca5e04928c606df2839",
        firstName: "Hermine",
        lastName: "Melkumyan",
        phone: "notDefined",
        email: "notDefined",
        education: "notDefined",
        workExperience: "notDefined",
        trainings: "Relq",
        imagePath: "./poto/HermineMelkumyan.jpg",
    },
    {
        id: "a721acbc804a1d89942ca6ff310a2b1a",
        firstName: "Hermine",
        lastName: "Sahakyan",
        phone: "notDefined",
        email: "notDefined",
        education: "notDefined",
        workExperience: "notDefined",
        trainings: "Relq",
        imagePath: "./poto/HermineSahakyan.jpg",
    },
    {
        id: "e8d1acc2ed2b0e34d1f29e52212f5e49",
        firstName: "Larine",
        lastName: "Danielyan",
        phone: "+374 97 75 95 99",
        email: "danielyanlari@gmail.com",
        education: "Economics and Menegment",
        workExperience: "Martuninsky district Medical Association",
        trainings: "Relq",
        imagePath: "./poto/LarineDanielyan.jpg",
    },
    {
        id: "e5ba3990fc9ef75ab56796eeb1dc2773",
        firstName: "Liana",
        lastName: "Dashyan",
        phone: "+374 91 55 53 74",
        email: "dashyanlian@gmail.com",
        education: "YSU",
        workExperience: "GYU NGO",
        trainings: "Relq",
        imagePath: "./poto/LianaDashyan.jpg",
    },
    {
        id: "8456043262b810baf28c7ae0ab2e4607",
        firstName: "Lusine",
        lastName: "Yeremyan",
        phone: "+374 43 18 18 34",
        email: "lusineer@gmail.com",
        education: "Economist",
        workExperience: "Municipality",
        trainings: "Relq, MIC",
        imagePath: "./poto/LusineYeremyan.jpg",
    },
    {
        id: "ecbd988eafa3d595b2cbccf155113662",
        firstName: "Lusine",
        lastName: "Petrosyan",
        phone: "+374 93 32 29 02",
        email: "plusine99@gmail.com",
        education: "Armenian State University faculty of Radiophysics",
        workExperience: "notDefined",
        trainings: "Relq",
        imagePath: "./poto/LusinePetrosyan.jpg",
    },
    {
        id: "aacf48d0ba2ce9439d0cfeed864e85c7",
        firstName: "Karen",
        lastName: "Darbinyan",
        phone: "+374 98 156 247",
        email: "kar31100@gmail.com",
        education: "YSU",
        workExperience: "alam asxarh",
        trainings: "RELQ",
        imagePath: "./poto/KarenDarbinyan.jpg",
    },
    {
        id: "9610620cadbb5216989043421cdc4b5e",
        firstName: "Marat",
        lastName: "Harutyunyan",
        phone: "+374 44 05 51 50",
        email: "maratharutyunyan.mh.mh@gmail.com",
        education: "ASIPCS",
        workExperience: "EL Market",
        trainings: "Relq School",
        imagePath: "./poto/MaratHarutyunyan.jpg",
    },
    {
        id: "aa50b8eb9207b1da8127d6bb79629afd",
        firstName: "Narek",
        lastName: "Tovmasyan",
        phone: "+374 94 27 67 00",
        email: "Narektom333@gmail.com",
        education: "ASUE",
        workExperience: "Ameria Bank",
        trainings: "Relq School",
        imagePath: "./poto/NarekTovmasyan.jpg",
    },
    {
        id: "d84cd8573db9890394ea2bcf7b736bea",
        firstName: "Seda",
        lastName: "Shahnazaryan",
        phone: "+374 98 31 38 71",
        email: "shahnazaryan.seda@mail.ru",
        education: "Higher Education:Historian",
        workExperience: "notDefined",
        trainings: "TechBoost4Women,RELQ technology school",
        imagePath: "./poto/SedaShahnazaryan.jpg",
    },
    {
        id: "b805d722720774a8ab681eb6716e0b0b",
        firstName: "Seryozha",
        lastName: "Asatryan",
        phone: "+374 94 24 68 80",
        email: "seryozha.asatryan02@gmail.com",
        education: "Economics",
        workExperience: "notDefined",
        trainings: "Relq School",
        imagePath: "./poto/SeryozhaAsatryan.jpg",
    },
    {
        id: "e4869bdc52121172d108840f23f66b1e",
        firstName: "Sevak",
        lastName: "Stepanyan",
        phone: "+374 77 12 16 96",
        email: "stepanyansevak9@gamil.com",
        education: "Economics and Menegment",
        workExperience: "notDefined",
        trainings: "Relq School",
        imagePath: "./poto/SevakStepanyan.jpg",
    },
    {
        id: "9ac1660ff57852bff4298300f7f72067",
        firstName: "Silva",
        lastName: "Ohanyan",
        phone: "notDefined",
        email: "notDefined",
        education: "notDefined",
        workExperience: "notDefined",
        trainings: "Relq School",
        imagePath: "./poto/SilvaOhanyan.jpg",
    },
    {
        id: "f9907bb6eb4e0037fbfc3dcce6c77dd8",
        firstName: "Suren",
        lastName: "Galstyan",
        phone: "notDefined",
        email: "notDefined",
        education: "notDefined",
        workExperience: "notDefined",
        trainings: "Relq School",
        imagePath: "./poto/SurenGalstyan.jpg",
    },
    {
        id: "dfb4e83ff97149bbb54b67fafd9f5a11",
        firstName: "Tigran",
        lastName: "Martirosyan",
        phone: "+374 77 15 18 68",
        email: "martirosyant01@mail.ru",
        education: "notDefined",
        workExperience: "notDefined",
        trainings: "Relq School",
        imagePath: "./poto/TigranMartirosyan.jpg",
    },
];